name: mad_histime
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_signin_button: ^1.0.0

  # for firestore
  google_sign_in: ^4.0.11
  firebase_auth: ^0.14.0+5
#  firebase_storage: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # for firestore
  cloud_firestore: ^0.12.10

flutter:
  uses-material-design: true
  assets:
    - image/logo_large.png
    - image/logo_small.png